# Compile with Watcom 10.6 or OpenWatcom

CC = wcc386
CFLAGS = -iAPP -iENGINE -iHAL -iDEPS\DATA -iDEPS\ENV /4r /s /otexan
OBJDIR = BIN

# Object files in BIN
OBJS = $(OBJDIR)\main.obj $(OBJDIR)\assets.obj $(OBJDIR)\data.obj $(OBJDIR)\vgaregs.obj $(OBJDIR)\video.obj $(OBJDIR)\env.obj $(OBJDIR)\input.obj $(OBJDIR)\log.obj $(OBJDIR)\math.obj

# Linker directive file
LNK = $(OBJDIR)\bmpio.lnk

# Final executable
bmpio.exe: $(OBJS)
	@%create $(LNK)
	@%append $(LNK) system dos4g
	@%append $(LNK) name bmpio
	@for %i in ($(OBJS)) do @%append $(LNK) file %i
	wlink @$(LNK)

# Compile rules for each .c -> .obj in BIN
$(OBJDIR)\vgaregs.obj: HAL\VGAREGS.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\video.obj: ENGINE\VIDEO.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\data.obj: DEPS\DATA\DATA.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\math.obj: ENGINE\MATH.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\env.obj: DEPS\ENV\ENV.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\log.obj: ENGINE\LOG\LOG.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\input.obj: ENGINE\INPUT.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\game.obj: ENGINE\GAME.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\assets.obj: ENGINE\ASSETS.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\engine.obj: ENGINE\ENGINE.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<

$(OBJDIR)\main.obj: APP\MAIN.C
	if not exist $(OBJDIR) mkdir $(OBJDIR)
	$(CC) $(CFLAGS) -fo=$@ $<



