#ifndef TEST_H
#define TEST_H

#include "ASSETS.H"
#include "GAME.H"

/* CONSTANTS ===========================================================================*/

/* PROTOTYPES ===========================================================================*/
bool t_initTests();
void t_createRenamon();
/* GLOBAL VARS =========================================================================*/
extern struct Color *testPalette;

#endif